//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.WebService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        WindowsFormsApp1.WebService1.RegistrationResponse Registration(WindowsFormsApp1.WebService1.RegistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.RegistrationResponse> RegistrationAsync(WindowsFormsApp1.WebService1.RegistrationRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SelectResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectResponse Select(WindowsFormsApp1.WebService1.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectResponse> SelectAsync(WindowsFormsApp1.WebService1.SelectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registration", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.WebService1.RegistrationRequestBody Body;
        
        public RegistrationRequest() {
        }
        
        public RegistrationRequest(WindowsFormsApp1.WebService1.RegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string role;
        
        public RegistrationRequestBody() {
        }
        
        public RegistrationRequestBody(string id, string first_name, string last_name, string role) {
            this.id = id;
            this.first_name = first_name;
            this.last_name = last_name;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.WebService1.RegistrationResponseBody Body;
        
        public RegistrationResponse() {
        }
        
        public RegistrationResponse(WindowsFormsApp1.WebService1.RegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegistrationResult;
        
        public RegistrationResponseBody() {
        }
        
        public RegistrationResponseBody(int RegistrationResult) {
            this.RegistrationResult = RegistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(WindowsFormsApp1.WebService1.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectRequestBody {
        
        public SelectRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(WindowsFormsApp1.WebService1.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectResult;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectResult) {
            this.SelectResult = SelectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.WebService1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.WebService1.WebService1Soap>, WindowsFormsApp1.WebService1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.RegistrationResponse WindowsFormsApp1.WebService1.WebService1Soap.Registration(WindowsFormsApp1.WebService1.RegistrationRequest request) {
            return base.Channel.Registration(request);
        }
        
        public int Registration(string id, string first_name, string last_name, string role) {
            WindowsFormsApp1.WebService1.RegistrationRequest inValue = new WindowsFormsApp1.WebService1.RegistrationRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.RegistrationRequestBody();
            inValue.Body.id = id;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.role = role;
            WindowsFormsApp1.WebService1.RegistrationResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).Registration(inValue);
            return retVal.Body.RegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.RegistrationResponse> WindowsFormsApp1.WebService1.WebService1Soap.RegistrationAsync(WindowsFormsApp1.WebService1.RegistrationRequest request) {
            return base.Channel.RegistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.RegistrationResponse> RegistrationAsync(string id, string first_name, string last_name, string role) {
            WindowsFormsApp1.WebService1.RegistrationRequest inValue = new WindowsFormsApp1.WebService1.RegistrationRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.RegistrationRequestBody();
            inValue.Body.id = id;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.role = role;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).RegistrationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectResponse WindowsFormsApp1.WebService1.WebService1Soap.Select(WindowsFormsApp1.WebService1.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] Select() {
            WindowsFormsApp1.WebService1.SelectRequest inValue = new WindowsFormsApp1.WebService1.SelectRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectRequestBody();
            WindowsFormsApp1.WebService1.SelectResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).Select(inValue);
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectAsync(WindowsFormsApp1.WebService1.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectResponse> SelectAsync() {
            WindowsFormsApp1.WebService1.SelectRequest inValue = new WindowsFormsApp1.WebService1.SelectRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectRequestBody();
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectAsync(inValue);
        }
    }
}
