//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.WebService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://wxwx.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wxwx.org/", ConfigurationName="WebService1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/Registration", ReplyAction="*")]
        WindowsFormsApp1.WebService1.RegistrationResponse Registration(WindowsFormsApp1.WebService1.RegistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/Registration", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.RegistrationResponse> RegistrationAsync(WindowsFormsApp1.WebService1.RegistrationRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/Authorization", ReplyAction="*")]
        WindowsFormsApp1.WebService1.AuthorizationResponse Authorization(WindowsFormsApp1.WebService1.AuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/Authorization", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.AuthorizationResponse> AuthorizationAsync(WindowsFormsApp1.WebService1.AuthorizationRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SelectResult из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/Select", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectResponse Select(WindowsFormsApp1.WebService1.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectResponse> SelectAsync(WindowsFormsApp1.WebService1.SelectRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/UpdateUser", ReplyAction="*")]
        WindowsFormsApp1.WebService1.UpdateUserResponse UpdateUser(WindowsFormsApp1.WebService1.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.UpdateUserResponse> UpdateUserAsync(WindowsFormsApp1.WebService1.UpdateUserRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteAdmin", ReplyAction="*")]
        WindowsFormsApp1.WebService1.DeleteAdminResponse DeleteAdmin(WindowsFormsApp1.WebService1.DeleteAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteAdminResponse> DeleteAdminAsync(WindowsFormsApp1.WebService1.DeleteAdminRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SelectAdminsResult из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectAdmins", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectAdminsResponse SelectAdmins(WindowsFormsApp1.WebService1.SelectAdminsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectAdmins", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectAdminsResponse> SelectAdminsAsync(WindowsFormsApp1.WebService1.SelectAdminsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем address из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/InsertWarehouse", ReplyAction="*")]
        WindowsFormsApp1.WebService1.InsertWarehouseResponse InsertWarehouse(WindowsFormsApp1.WebService1.InsertWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/InsertWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertWarehouseResponse> InsertWarehouseAsync(WindowsFormsApp1.WebService1.InsertWarehouseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SelectWarehousesResult из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectWarehouses", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectWarehousesResponse SelectWarehouses(WindowsFormsApp1.WebService1.SelectWarehousesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectWarehouses", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectWarehousesResponse> SelectWarehousesAsync(WindowsFormsApp1.WebService1.SelectWarehousesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteWarehouse", ReplyAction="*")]
        WindowsFormsApp1.WebService1.DeleteWarehouseResponse DeleteWarehouse(WindowsFormsApp1.WebService1.DeleteWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteWarehouseResponse> DeleteWarehouseAsync(WindowsFormsApp1.WebService1.DeleteWarehouseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/AddInWarehouse", ReplyAction="*")]
        WindowsFormsApp1.WebService1.AddInWarehouseResponse AddInWarehouse(WindowsFormsApp1.WebService1.AddInWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/AddInWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.AddInWarehouseResponse> AddInWarehouseAsync(WindowsFormsApp1.WebService1.AddInWarehouseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DelInWarehouse", ReplyAction="*")]
        WindowsFormsApp1.WebService1.DelInWarehouseResponse DelInWarehouse(WindowsFormsApp1.WebService1.DelInWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DelInWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DelInWarehouseResponse> DelInWarehouseAsync(WindowsFormsApp1.WebService1.DelInWarehouseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/InsertParcel", ReplyAction="*")]
        WindowsFormsApp1.WebService1.InsertParcelResponse InsertParcel(WindowsFormsApp1.WebService1.InsertParcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/InsertParcel", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertParcelResponse> InsertParcelAsync(WindowsFormsApp1.WebService1.InsertParcelRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SelectParcelsResult из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectParcels", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectParcelsResponse SelectParcels(WindowsFormsApp1.WebService1.SelectParcelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectParcels", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectParcelsResponse> SelectParcelsAsync(WindowsFormsApp1.WebService1.SelectParcelsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectUserParcels", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectUserParcelsResponse SelectUserParcels(WindowsFormsApp1.WebService1.SelectUserParcelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectUserParcels", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectUserParcelsResponse> SelectUserParcelsAsync(WindowsFormsApp1.WebService1.SelectUserParcelsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteParcel", ReplyAction="*")]
        WindowsFormsApp1.WebService1.DeleteParcelResponse DeleteParcel(WindowsFormsApp1.WebService1.DeleteParcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteParcel", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteParcelResponse> DeleteParcelAsync(WindowsFormsApp1.WebService1.DeleteParcelRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем passport из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/InsertLink", ReplyAction="*")]
        WindowsFormsApp1.WebService1.InsertLinkResponse InsertLink(WindowsFormsApp1.WebService1.InsertLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/InsertLink", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertLinkResponse> InsertLinkAsync(WindowsFormsApp1.WebService1.InsertLinkRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SelectLinkResult из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectLink", ReplyAction="*")]
        WindowsFormsApp1.WebService1.SelectLinkResponse SelectLink(WindowsFormsApp1.WebService1.SelectLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/SelectLink", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectLinkResponse> SelectLinkAsync(WindowsFormsApp1.WebService1.SelectLinkRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://wxwx.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteLink", ReplyAction="*")]
        WindowsFormsApp1.WebService1.DeleteLinkResponse DeleteLink(WindowsFormsApp1.WebService1.DeleteLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wxwx.org/DeleteLink", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteLinkResponse> DeleteLinkAsync(WindowsFormsApp1.WebService1.DeleteLinkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registration", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.RegistrationRequestBody Body;
        
        public RegistrationRequest() {
        }
        
        public RegistrationRequest(WindowsFormsApp1.WebService1.RegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class RegistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string role;
        
        public RegistrationRequestBody() {
        }
        
        public RegistrationRequestBody(string login, string password, string first_name, string last_name, string role) {
            this.login = login;
            this.password = password;
            this.first_name = first_name;
            this.last_name = last_name;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrationResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.RegistrationResponseBody Body;
        
        public RegistrationResponse() {
        }
        
        public RegistrationResponse(WindowsFormsApp1.WebService1.RegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class RegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegistrationResult;
        
        public RegistrationResponseBody() {
        }
        
        public RegistrationResponseBody(int RegistrationResult) {
            this.RegistrationResult = RegistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorization", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.AuthorizationRequestBody Body;
        
        public AuthorizationRequest() {
        }
        
        public AuthorizationRequest(WindowsFormsApp1.WebService1.AuthorizationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class AuthorizationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthorizationRequestBody() {
        }
        
        public AuthorizationRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizationResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.AuthorizationResponseBody Body;
        
        public AuthorizationResponse() {
        }
        
        public AuthorizationResponse(WindowsFormsApp1.WebService1.AuthorizationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class AuthorizationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString AuthorizationResult;
        
        public AuthorizationResponseBody() {
        }
        
        public AuthorizationResponseBody(WindowsFormsApp1.WebService1.ArrayOfString AuthorizationResult) {
            this.AuthorizationResult = AuthorizationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(WindowsFormsApp1.WebService1.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectRequestBody {
        
        public SelectRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(WindowsFormsApp1.WebService1.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectResult;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectResult) {
            this.SelectResult = SelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(WindowsFormsApp1.WebService1.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(WindowsFormsApp1.WebService1.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserResponseBody {
        
        public UpdateUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAdmin", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteAdminRequestBody Body;
        
        public DeleteAdminRequest() {
        }
        
        public DeleteAdminRequest(WindowsFormsApp1.WebService1.DeleteAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class DeleteAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteAdminRequestBody() {
        }
        
        public DeleteAdminRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAdminResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteAdminResponseBody Body;
        
        public DeleteAdminResponse() {
        }
        
        public DeleteAdminResponse(WindowsFormsApp1.WebService1.DeleteAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteAdminResponseBody {
        
        public DeleteAdminResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAdminsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAdmins", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectAdminsRequestBody Body;
        
        public SelectAdminsRequest() {
        }
        
        public SelectAdminsRequest(WindowsFormsApp1.WebService1.SelectAdminsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAdminsRequestBody {
        
        public SelectAdminsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAdminsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAdminsResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectAdminsResponseBody Body;
        
        public SelectAdminsResponse() {
        }
        
        public SelectAdminsResponse(WindowsFormsApp1.WebService1.SelectAdminsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectAdminsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectAdminsResult;
        
        public SelectAdminsResponseBody() {
        }
        
        public SelectAdminsResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectAdminsResult) {
            this.SelectAdminsResult = SelectAdminsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWarehouse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.InsertWarehouseRequestBody Body;
        
        public InsertWarehouseRequest() {
        }
        
        public InsertWarehouseRequest(WindowsFormsApp1.WebService1.InsertWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class InsertWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string capacity;
        
        public InsertWarehouseRequestBody() {
        }
        
        public InsertWarehouseRequestBody(string address, string capacity) {
            this.address = address;
            this.capacity = capacity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWarehouseResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.InsertWarehouseResponseBody Body;
        
        public InsertWarehouseResponse() {
        }
        
        public InsertWarehouseResponse(WindowsFormsApp1.WebService1.InsertWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertWarehouseResponseBody {
        
        public InsertWarehouseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectWarehousesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectWarehouses", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectWarehousesRequestBody Body;
        
        public SelectWarehousesRequest() {
        }
        
        public SelectWarehousesRequest(WindowsFormsApp1.WebService1.SelectWarehousesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectWarehousesRequestBody {
        
        public SelectWarehousesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectWarehousesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectWarehousesResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectWarehousesResponseBody Body;
        
        public SelectWarehousesResponse() {
        }
        
        public SelectWarehousesResponse(WindowsFormsApp1.WebService1.SelectWarehousesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectWarehousesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectWarehousesResult;
        
        public SelectWarehousesResponseBody() {
        }
        
        public SelectWarehousesResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectWarehousesResult) {
            this.SelectWarehousesResult = SelectWarehousesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWarehouse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteWarehouseRequestBody Body;
        
        public DeleteWarehouseRequest() {
        }
        
        public DeleteWarehouseRequest(WindowsFormsApp1.WebService1.DeleteWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class DeleteWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteWarehouseRequestBody() {
        }
        
        public DeleteWarehouseRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWarehouseResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteWarehouseResponseBody Body;
        
        public DeleteWarehouseResponse() {
        }
        
        public DeleteWarehouseResponse(WindowsFormsApp1.WebService1.DeleteWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteWarehouseResponseBody {
        
        public DeleteWarehouseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddInWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddInWarehouse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.AddInWarehouseRequestBody Body;
        
        public AddInWarehouseRequest() {
        }
        
        public AddInWarehouseRequest(WindowsFormsApp1.WebService1.AddInWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class AddInWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public AddInWarehouseRequestBody() {
        }
        
        public AddInWarehouseRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddInWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddInWarehouseResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.AddInWarehouseResponseBody Body;
        
        public AddInWarehouseResponse() {
        }
        
        public AddInWarehouseResponse(WindowsFormsApp1.WebService1.AddInWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddInWarehouseResponseBody {
        
        public AddInWarehouseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelInWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelInWarehouse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DelInWarehouseRequestBody Body;
        
        public DelInWarehouseRequest() {
        }
        
        public DelInWarehouseRequest(WindowsFormsApp1.WebService1.DelInWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class DelInWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DelInWarehouseRequestBody() {
        }
        
        public DelInWarehouseRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelInWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelInWarehouseResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DelInWarehouseResponseBody Body;
        
        public DelInWarehouseResponse() {
        }
        
        public DelInWarehouseResponse(WindowsFormsApp1.WebService1.DelInWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DelInWarehouseResponseBody {
        
        public DelInWarehouseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertParcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertParcel", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.InsertParcelRequestBody Body;
        
        public InsertParcelRequest() {
        }
        
        public InsertParcelRequest(WindowsFormsApp1.WebService1.InsertParcelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class InsertParcelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string warehouse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime date;
        
        public InsertParcelRequestBody() {
        }
        
        public InsertParcelRequestBody(string id, string name, string warehouse, System.DateTime date) {
            this.id = id;
            this.name = name;
            this.warehouse = warehouse;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertParcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertParcelResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.InsertParcelResponseBody Body;
        
        public InsertParcelResponse() {
        }
        
        public InsertParcelResponse(WindowsFormsApp1.WebService1.InsertParcelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertParcelResponseBody {
        
        public InsertParcelResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectParcelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectParcels", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectParcelsRequestBody Body;
        
        public SelectParcelsRequest() {
        }
        
        public SelectParcelsRequest(WindowsFormsApp1.WebService1.SelectParcelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectParcelsRequestBody {
        
        public SelectParcelsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectParcelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectParcelsResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectParcelsResponseBody Body;
        
        public SelectParcelsResponse() {
        }
        
        public SelectParcelsResponse(WindowsFormsApp1.WebService1.SelectParcelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectParcelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectParcelsResult;
        
        public SelectParcelsResponseBody() {
        }
        
        public SelectParcelsResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectParcelsResult) {
            this.SelectParcelsResult = SelectParcelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectUserParcelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectUserParcels", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectUserParcelsRequestBody Body;
        
        public SelectUserParcelsRequest() {
        }
        
        public SelectUserParcelsRequest(WindowsFormsApp1.WebService1.SelectUserParcelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectUserParcelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public SelectUserParcelsRequestBody() {
        }
        
        public SelectUserParcelsRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectUserParcelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectUserParcelsResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectUserParcelsResponseBody Body;
        
        public SelectUserParcelsResponse() {
        }
        
        public SelectUserParcelsResponse(WindowsFormsApp1.WebService1.SelectUserParcelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectUserParcelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectUserParcelsResult;
        
        public SelectUserParcelsResponseBody() {
        }
        
        public SelectUserParcelsResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectUserParcelsResult) {
            this.SelectUserParcelsResult = SelectUserParcelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteParcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteParcel", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteParcelRequestBody Body;
        
        public DeleteParcelRequest() {
        }
        
        public DeleteParcelRequest(WindowsFormsApp1.WebService1.DeleteParcelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class DeleteParcelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteParcelRequestBody() {
        }
        
        public DeleteParcelRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteParcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteParcelResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteParcelResponseBody Body;
        
        public DeleteParcelResponse() {
        }
        
        public DeleteParcelResponse(WindowsFormsApp1.WebService1.DeleteParcelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteParcelResponseBody {
        
        public DeleteParcelResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertLink", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.InsertLinkRequestBody Body;
        
        public InsertLinkRequest() {
        }
        
        public InsertLinkRequest(WindowsFormsApp1.WebService1.InsertLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class InsertLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passport;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string number;
        
        public InsertLinkRequestBody() {
        }
        
        public InsertLinkRequestBody(string passport, string number) {
            this.passport = passport;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertLinkResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.InsertLinkResponseBody Body;
        
        public InsertLinkResponse() {
        }
        
        public InsertLinkResponse(WindowsFormsApp1.WebService1.InsertLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertLinkResponseBody {
        
        public InsertLinkResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectLink", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectLinkRequestBody Body;
        
        public SelectLinkRequest() {
        }
        
        public SelectLinkRequest(WindowsFormsApp1.WebService1.SelectLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectLinkRequestBody {
        
        public SelectLinkRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectLinkResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.SelectLinkResponseBody Body;
        
        public SelectLinkResponse() {
        }
        
        public SelectLinkResponse(WindowsFormsApp1.WebService1.SelectLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class SelectLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectLinkResult;
        
        public SelectLinkResponseBody() {
        }
        
        public SelectLinkResponseBody(WindowsFormsApp1.WebService1.ArrayOfString[] SelectLinkResult) {
            this.SelectLinkResult = SelectLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLink", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteLinkRequestBody Body;
        
        public DeleteLinkRequest() {
        }
        
        public DeleteLinkRequest(WindowsFormsApp1.WebService1.DeleteLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wxwx.org/")]
    public partial class DeleteLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteLinkRequestBody() {
        }
        
        public DeleteLinkRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLinkResponse", Namespace="http://wxwx.org/", Order=0)]
        public WindowsFormsApp1.WebService1.DeleteLinkResponseBody Body;
        
        public DeleteLinkResponse() {
        }
        
        public DeleteLinkResponse(WindowsFormsApp1.WebService1.DeleteLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteLinkResponseBody {
        
        public DeleteLinkResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.WebService1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.WebService1.WebService1Soap>, WindowsFormsApp1.WebService1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.RegistrationResponse WindowsFormsApp1.WebService1.WebService1Soap.Registration(WindowsFormsApp1.WebService1.RegistrationRequest request) {
            return base.Channel.Registration(request);
        }
        
        public int Registration(string login, string password, string first_name, string last_name, string role) {
            WindowsFormsApp1.WebService1.RegistrationRequest inValue = new WindowsFormsApp1.WebService1.RegistrationRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.RegistrationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.role = role;
            WindowsFormsApp1.WebService1.RegistrationResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).Registration(inValue);
            return retVal.Body.RegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.RegistrationResponse> WindowsFormsApp1.WebService1.WebService1Soap.RegistrationAsync(WindowsFormsApp1.WebService1.RegistrationRequest request) {
            return base.Channel.RegistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.RegistrationResponse> RegistrationAsync(string login, string password, string first_name, string last_name, string role) {
            WindowsFormsApp1.WebService1.RegistrationRequest inValue = new WindowsFormsApp1.WebService1.RegistrationRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.RegistrationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.role = role;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).RegistrationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.AuthorizationResponse WindowsFormsApp1.WebService1.WebService1Soap.Authorization(WindowsFormsApp1.WebService1.AuthorizationRequest request) {
            return base.Channel.Authorization(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString Authorization(string login, string password) {
            WindowsFormsApp1.WebService1.AuthorizationRequest inValue = new WindowsFormsApp1.WebService1.AuthorizationRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.AuthorizationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            WindowsFormsApp1.WebService1.AuthorizationResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).Authorization(inValue);
            return retVal.Body.AuthorizationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.AuthorizationResponse> WindowsFormsApp1.WebService1.WebService1Soap.AuthorizationAsync(WindowsFormsApp1.WebService1.AuthorizationRequest request) {
            return base.Channel.AuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.AuthorizationResponse> AuthorizationAsync(string login, string password) {
            WindowsFormsApp1.WebService1.AuthorizationRequest inValue = new WindowsFormsApp1.WebService1.AuthorizationRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.AuthorizationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).AuthorizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectResponse WindowsFormsApp1.WebService1.WebService1Soap.Select(WindowsFormsApp1.WebService1.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] Select() {
            WindowsFormsApp1.WebService1.SelectRequest inValue = new WindowsFormsApp1.WebService1.SelectRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectRequestBody();
            WindowsFormsApp1.WebService1.SelectResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).Select(inValue);
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectAsync(WindowsFormsApp1.WebService1.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectResponse> SelectAsync() {
            WindowsFormsApp1.WebService1.SelectRequest inValue = new WindowsFormsApp1.WebService1.SelectRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectRequestBody();
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.UpdateUserResponse WindowsFormsApp1.WebService1.WebService1Soap.UpdateUser(WindowsFormsApp1.WebService1.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public void UpdateUser(string id) {
            WindowsFormsApp1.WebService1.UpdateUserRequest inValue = new WindowsFormsApp1.WebService1.UpdateUserRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.UpdateUserRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.UpdateUserResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).UpdateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.UpdateUserResponse> WindowsFormsApp1.WebService1.WebService1Soap.UpdateUserAsync(WindowsFormsApp1.WebService1.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.UpdateUserResponse> UpdateUserAsync(string id) {
            WindowsFormsApp1.WebService1.UpdateUserRequest inValue = new WindowsFormsApp1.WebService1.UpdateUserRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.UpdateUserRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.DeleteAdminResponse WindowsFormsApp1.WebService1.WebService1Soap.DeleteAdmin(WindowsFormsApp1.WebService1.DeleteAdminRequest request) {
            return base.Channel.DeleteAdmin(request);
        }
        
        public void DeleteAdmin(string id) {
            WindowsFormsApp1.WebService1.DeleteAdminRequest inValue = new WindowsFormsApp1.WebService1.DeleteAdminRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteAdminRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.DeleteAdminResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteAdmin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteAdminResponse> WindowsFormsApp1.WebService1.WebService1Soap.DeleteAdminAsync(WindowsFormsApp1.WebService1.DeleteAdminRequest request) {
            return base.Channel.DeleteAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteAdminResponse> DeleteAdminAsync(string id) {
            WindowsFormsApp1.WebService1.DeleteAdminRequest inValue = new WindowsFormsApp1.WebService1.DeleteAdminRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteAdminRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectAdminsResponse WindowsFormsApp1.WebService1.WebService1Soap.SelectAdmins(WindowsFormsApp1.WebService1.SelectAdminsRequest request) {
            return base.Channel.SelectAdmins(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectAdmins() {
            WindowsFormsApp1.WebService1.SelectAdminsRequest inValue = new WindowsFormsApp1.WebService1.SelectAdminsRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectAdminsRequestBody();
            WindowsFormsApp1.WebService1.SelectAdminsResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectAdmins(inValue);
            return retVal.Body.SelectAdminsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectAdminsResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectAdminsAsync(WindowsFormsApp1.WebService1.SelectAdminsRequest request) {
            return base.Channel.SelectAdminsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectAdminsResponse> SelectAdminsAsync() {
            WindowsFormsApp1.WebService1.SelectAdminsRequest inValue = new WindowsFormsApp1.WebService1.SelectAdminsRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectAdminsRequestBody();
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectAdminsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.InsertWarehouseResponse WindowsFormsApp1.WebService1.WebService1Soap.InsertWarehouse(WindowsFormsApp1.WebService1.InsertWarehouseRequest request) {
            return base.Channel.InsertWarehouse(request);
        }
        
        public void InsertWarehouse(string address, string capacity) {
            WindowsFormsApp1.WebService1.InsertWarehouseRequest inValue = new WindowsFormsApp1.WebService1.InsertWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.InsertWarehouseRequestBody();
            inValue.Body.address = address;
            inValue.Body.capacity = capacity;
            WindowsFormsApp1.WebService1.InsertWarehouseResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).InsertWarehouse(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertWarehouseResponse> WindowsFormsApp1.WebService1.WebService1Soap.InsertWarehouseAsync(WindowsFormsApp1.WebService1.InsertWarehouseRequest request) {
            return base.Channel.InsertWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertWarehouseResponse> InsertWarehouseAsync(string address, string capacity) {
            WindowsFormsApp1.WebService1.InsertWarehouseRequest inValue = new WindowsFormsApp1.WebService1.InsertWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.InsertWarehouseRequestBody();
            inValue.Body.address = address;
            inValue.Body.capacity = capacity;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).InsertWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectWarehousesResponse WindowsFormsApp1.WebService1.WebService1Soap.SelectWarehouses(WindowsFormsApp1.WebService1.SelectWarehousesRequest request) {
            return base.Channel.SelectWarehouses(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectWarehouses() {
            WindowsFormsApp1.WebService1.SelectWarehousesRequest inValue = new WindowsFormsApp1.WebService1.SelectWarehousesRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectWarehousesRequestBody();
            WindowsFormsApp1.WebService1.SelectWarehousesResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectWarehouses(inValue);
            return retVal.Body.SelectWarehousesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectWarehousesResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectWarehousesAsync(WindowsFormsApp1.WebService1.SelectWarehousesRequest request) {
            return base.Channel.SelectWarehousesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectWarehousesResponse> SelectWarehousesAsync() {
            WindowsFormsApp1.WebService1.SelectWarehousesRequest inValue = new WindowsFormsApp1.WebService1.SelectWarehousesRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectWarehousesRequestBody();
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectWarehousesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.DeleteWarehouseResponse WindowsFormsApp1.WebService1.WebService1Soap.DeleteWarehouse(WindowsFormsApp1.WebService1.DeleteWarehouseRequest request) {
            return base.Channel.DeleteWarehouse(request);
        }
        
        public void DeleteWarehouse(string id) {
            WindowsFormsApp1.WebService1.DeleteWarehouseRequest inValue = new WindowsFormsApp1.WebService1.DeleteWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteWarehouseRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.DeleteWarehouseResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteWarehouse(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteWarehouseResponse> WindowsFormsApp1.WebService1.WebService1Soap.DeleteWarehouseAsync(WindowsFormsApp1.WebService1.DeleteWarehouseRequest request) {
            return base.Channel.DeleteWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteWarehouseResponse> DeleteWarehouseAsync(string id) {
            WindowsFormsApp1.WebService1.DeleteWarehouseRequest inValue = new WindowsFormsApp1.WebService1.DeleteWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteWarehouseRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.AddInWarehouseResponse WindowsFormsApp1.WebService1.WebService1Soap.AddInWarehouse(WindowsFormsApp1.WebService1.AddInWarehouseRequest request) {
            return base.Channel.AddInWarehouse(request);
        }
        
        public void AddInWarehouse(string id) {
            WindowsFormsApp1.WebService1.AddInWarehouseRequest inValue = new WindowsFormsApp1.WebService1.AddInWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.AddInWarehouseRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.AddInWarehouseResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).AddInWarehouse(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.AddInWarehouseResponse> WindowsFormsApp1.WebService1.WebService1Soap.AddInWarehouseAsync(WindowsFormsApp1.WebService1.AddInWarehouseRequest request) {
            return base.Channel.AddInWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.AddInWarehouseResponse> AddInWarehouseAsync(string id) {
            WindowsFormsApp1.WebService1.AddInWarehouseRequest inValue = new WindowsFormsApp1.WebService1.AddInWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.AddInWarehouseRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).AddInWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.DelInWarehouseResponse WindowsFormsApp1.WebService1.WebService1Soap.DelInWarehouse(WindowsFormsApp1.WebService1.DelInWarehouseRequest request) {
            return base.Channel.DelInWarehouse(request);
        }
        
        public void DelInWarehouse(string id) {
            WindowsFormsApp1.WebService1.DelInWarehouseRequest inValue = new WindowsFormsApp1.WebService1.DelInWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DelInWarehouseRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.DelInWarehouseResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DelInWarehouse(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DelInWarehouseResponse> WindowsFormsApp1.WebService1.WebService1Soap.DelInWarehouseAsync(WindowsFormsApp1.WebService1.DelInWarehouseRequest request) {
            return base.Channel.DelInWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DelInWarehouseResponse> DelInWarehouseAsync(string id) {
            WindowsFormsApp1.WebService1.DelInWarehouseRequest inValue = new WindowsFormsApp1.WebService1.DelInWarehouseRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DelInWarehouseRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DelInWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.InsertParcelResponse WindowsFormsApp1.WebService1.WebService1Soap.InsertParcel(WindowsFormsApp1.WebService1.InsertParcelRequest request) {
            return base.Channel.InsertParcel(request);
        }
        
        public void InsertParcel(string id, string name, string warehouse, System.DateTime date) {
            WindowsFormsApp1.WebService1.InsertParcelRequest inValue = new WindowsFormsApp1.WebService1.InsertParcelRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.InsertParcelRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.warehouse = warehouse;
            inValue.Body.date = date;
            WindowsFormsApp1.WebService1.InsertParcelResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).InsertParcel(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertParcelResponse> WindowsFormsApp1.WebService1.WebService1Soap.InsertParcelAsync(WindowsFormsApp1.WebService1.InsertParcelRequest request) {
            return base.Channel.InsertParcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertParcelResponse> InsertParcelAsync(string id, string name, string warehouse, System.DateTime date) {
            WindowsFormsApp1.WebService1.InsertParcelRequest inValue = new WindowsFormsApp1.WebService1.InsertParcelRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.InsertParcelRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.warehouse = warehouse;
            inValue.Body.date = date;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).InsertParcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectParcelsResponse WindowsFormsApp1.WebService1.WebService1Soap.SelectParcels(WindowsFormsApp1.WebService1.SelectParcelsRequest request) {
            return base.Channel.SelectParcels(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectParcels() {
            WindowsFormsApp1.WebService1.SelectParcelsRequest inValue = new WindowsFormsApp1.WebService1.SelectParcelsRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectParcelsRequestBody();
            WindowsFormsApp1.WebService1.SelectParcelsResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectParcels(inValue);
            return retVal.Body.SelectParcelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectParcelsResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectParcelsAsync(WindowsFormsApp1.WebService1.SelectParcelsRequest request) {
            return base.Channel.SelectParcelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectParcelsResponse> SelectParcelsAsync() {
            WindowsFormsApp1.WebService1.SelectParcelsRequest inValue = new WindowsFormsApp1.WebService1.SelectParcelsRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectParcelsRequestBody();
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectParcelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectUserParcelsResponse WindowsFormsApp1.WebService1.WebService1Soap.SelectUserParcels(WindowsFormsApp1.WebService1.SelectUserParcelsRequest request) {
            return base.Channel.SelectUserParcels(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectUserParcels(string id) {
            WindowsFormsApp1.WebService1.SelectUserParcelsRequest inValue = new WindowsFormsApp1.WebService1.SelectUserParcelsRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectUserParcelsRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.SelectUserParcelsResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectUserParcels(inValue);
            return retVal.Body.SelectUserParcelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectUserParcelsResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectUserParcelsAsync(WindowsFormsApp1.WebService1.SelectUserParcelsRequest request) {
            return base.Channel.SelectUserParcelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectUserParcelsResponse> SelectUserParcelsAsync(string id) {
            WindowsFormsApp1.WebService1.SelectUserParcelsRequest inValue = new WindowsFormsApp1.WebService1.SelectUserParcelsRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectUserParcelsRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectUserParcelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.DeleteParcelResponse WindowsFormsApp1.WebService1.WebService1Soap.DeleteParcel(WindowsFormsApp1.WebService1.DeleteParcelRequest request) {
            return base.Channel.DeleteParcel(request);
        }
        
        public void DeleteParcel(string id) {
            WindowsFormsApp1.WebService1.DeleteParcelRequest inValue = new WindowsFormsApp1.WebService1.DeleteParcelRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteParcelRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.DeleteParcelResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteParcel(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteParcelResponse> WindowsFormsApp1.WebService1.WebService1Soap.DeleteParcelAsync(WindowsFormsApp1.WebService1.DeleteParcelRequest request) {
            return base.Channel.DeleteParcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteParcelResponse> DeleteParcelAsync(string id) {
            WindowsFormsApp1.WebService1.DeleteParcelRequest inValue = new WindowsFormsApp1.WebService1.DeleteParcelRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteParcelRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteParcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.InsertLinkResponse WindowsFormsApp1.WebService1.WebService1Soap.InsertLink(WindowsFormsApp1.WebService1.InsertLinkRequest request) {
            return base.Channel.InsertLink(request);
        }
        
        public void InsertLink(string passport, string number) {
            WindowsFormsApp1.WebService1.InsertLinkRequest inValue = new WindowsFormsApp1.WebService1.InsertLinkRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.InsertLinkRequestBody();
            inValue.Body.passport = passport;
            inValue.Body.number = number;
            WindowsFormsApp1.WebService1.InsertLinkResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).InsertLink(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertLinkResponse> WindowsFormsApp1.WebService1.WebService1Soap.InsertLinkAsync(WindowsFormsApp1.WebService1.InsertLinkRequest request) {
            return base.Channel.InsertLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.InsertLinkResponse> InsertLinkAsync(string passport, string number) {
            WindowsFormsApp1.WebService1.InsertLinkRequest inValue = new WindowsFormsApp1.WebService1.InsertLinkRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.InsertLinkRequestBody();
            inValue.Body.passport = passport;
            inValue.Body.number = number;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).InsertLinkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.SelectLinkResponse WindowsFormsApp1.WebService1.WebService1Soap.SelectLink(WindowsFormsApp1.WebService1.SelectLinkRequest request) {
            return base.Channel.SelectLink(request);
        }
        
        public WindowsFormsApp1.WebService1.ArrayOfString[] SelectLink() {
            WindowsFormsApp1.WebService1.SelectLinkRequest inValue = new WindowsFormsApp1.WebService1.SelectLinkRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectLinkRequestBody();
            WindowsFormsApp1.WebService1.SelectLinkResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectLink(inValue);
            return retVal.Body.SelectLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectLinkResponse> WindowsFormsApp1.WebService1.WebService1Soap.SelectLinkAsync(WindowsFormsApp1.WebService1.SelectLinkRequest request) {
            return base.Channel.SelectLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.SelectLinkResponse> SelectLinkAsync() {
            WindowsFormsApp1.WebService1.SelectLinkRequest inValue = new WindowsFormsApp1.WebService1.SelectLinkRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.SelectLinkRequestBody();
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).SelectLinkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.WebService1.DeleteLinkResponse WindowsFormsApp1.WebService1.WebService1Soap.DeleteLink(WindowsFormsApp1.WebService1.DeleteLinkRequest request) {
            return base.Channel.DeleteLink(request);
        }
        
        public void DeleteLink(string id) {
            WindowsFormsApp1.WebService1.DeleteLinkRequest inValue = new WindowsFormsApp1.WebService1.DeleteLinkRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteLinkRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.WebService1.DeleteLinkResponse retVal = ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteLink(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteLinkResponse> WindowsFormsApp1.WebService1.WebService1Soap.DeleteLinkAsync(WindowsFormsApp1.WebService1.DeleteLinkRequest request) {
            return base.Channel.DeleteLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WebService1.DeleteLinkResponse> DeleteLinkAsync(string id) {
            WindowsFormsApp1.WebService1.DeleteLinkRequest inValue = new WindowsFormsApp1.WebService1.DeleteLinkRequest();
            inValue.Body = new WindowsFormsApp1.WebService1.DeleteLinkRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.WebService1.WebService1Soap)(this)).DeleteLinkAsync(inValue);
        }
    }
}
